DO $$ BEGIN CREATE TYPE public.app_role AS ENUM ('owner', 'manager', 'warehouse_cn', 'warehouse_ca', 'driver', 'pickup_point', 'sales', 'support', 'customer'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.batch_method AS ENUM ('air', 'sea', 'express'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.batch_status AS ENUM ('draft', 'locked', 'shipped', 'arrived', 'closed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.cms_status AS ENUM ('draft', 'published', 'archived'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.coupon_type AS ENUM ('fixed', 'percent'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.fee_scheme_preference AS ENUM ('merged', 'split'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.inv_reason AS ENUM ('in', 'out', 'adjust', 'sale', 'return'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.invoice_status AS ENUM ('unpaid', 'paid', 'overdue', 'void'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.invoice_type AS ENUM ('waybill', 'batch', 'monthly', 'manual', 'shop'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.order_status AS ENUM ('pending', 'paid', 'procurement', 'received', 'packed', 'in_transit', 'ready_pickup', 'processing', 'shipped', 'delivered', 'cancelled', 'storage', 'arrived'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.product_purchase_type AS ENUM ('personal', 'business'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.product_status AS ENUM ('draft', 'active', 'archived'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.promo_type AS ENUM ('discount', 'bundle', 'flash'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.surcharge_scope AS ENUM ('waybill', 'carton', 'pallet', 'batch', 'forwarding'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.vip_level AS ENUM ('normal', 'silver', 'gold', 'diamond'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.waybill_status AS ENUM ('pending', 'received', 'packed', 'shipped', 'in_transit', 'ready_pickup', 'delivered', 'cancelled', 'procurement', 'storage', 'arrived'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE public.addresses (city text NOT NULL, country text DEFAULT '' NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, destination_code text, id uuid DEFAULT gen_random_uuid() NOT NULL, is_default boolean DEFAULT false NOT NULL, line1 text NOT NULL, line2 text, phone text NOT NULL, postal_code text NOT NULL, province text NOT NULL, recipient text NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, user_id uuid NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.addresses TO authenticated; GRANT ALL ON public.addresses TO service_role;
CREATE TABLE public.admin_action_logs (action text NOT NULL, after jsonb, before jsonb, created_at timestamptz DEFAULT now() NOT NULL, entity_id uuid NOT NULL, entity_type text NOT NULL, id uuid DEFAULT gen_random_uuid() NOT NULL, note text, operator_id uuid, operator_name text, PRIMARY KEY (id));
ALTER TABLE public.admin_action_logs ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.admin_action_logs TO authenticated; GRANT ALL ON public.admin_action_logs TO service_role;
CREATE TABLE public.admin_nav_items (group_sort_order integer DEFAULT 0 NOT NULL, group_title text DEFAULT '' NOT NULL, icon text NOT NULL, id uuid DEFAULT gen_random_uuid() NOT NULL, item_sort_order integer DEFAULT 0 NOT NULL, label text NOT NULL, path text NOT NULL, roles text[] DEFAULT '{}'::text[] NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.admin_nav_items ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.admin_nav_items TO authenticated; GRANT ALL ON public.admin_nav_items TO service_role;
CREATE TABLE public.ai_forwarding_drafts (confirmed_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL, draft_data jsonb DEFAULT '{}'::jsonb NOT NULL, expires_at timestamptz DEFAULT now() NOT NULL, forwarding_id uuid, id uuid DEFAULT gen_random_uuid() NOT NULL, request_no text, status text DEFAULT '' NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, user_id uuid NOT NULL, version integer DEFAULT 0 NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.ai_forwarding_drafts ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.ai_forwarding_drafts TO authenticated; GRANT ALL ON public.ai_forwarding_drafts TO service_role;
CREATE TABLE public.ai_forwarding_requests (created_at timestamptz DEFAULT now() NOT NULL, domestic_tracking_no text, forwarding_id uuid, id uuid DEFAULT gen_random_uuid() NOT NULL, idempotency_key text NOT NULL, payload jsonb, request_no text, source text DEFAULT '' NOT NULL, user_id uuid NOT NULL, visitor_biz_id uuid NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.ai_forwarding_requests ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.ai_forwarding_requests TO authenticated; GRANT ALL ON public.ai_forwarding_requests TO service_role;
CREATE TABLE public.ai_support_messages (body text NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, customer_user_id uuid NOT NULL, id uuid DEFAULT gen_random_uuid() NOT NULL, read_by_customer_at timestamptz, read_by_staff_at timestamptz, sender_role text NOT NULL, sender_user_id uuid, source text DEFAULT '' NOT NULL, thread_id uuid NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.ai_support_messages ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.ai_support_messages TO authenticated; GRANT ALL ON public.ai_support_messages TO service_role;
CREATE TABLE public.ai_support_threads (created_at timestamptz DEFAULT now() NOT NULL, customer_code text NOT NULL, customer_user_id uuid NOT NULL, id uuid DEFAULT gen_random_uuid() NOT NULL, last_message_at timestamptz DEFAULT now() NOT NULL, unread_for_customer numeric DEFAULT 0 NOT NULL, unread_for_staff numeric DEFAULT 0 NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.ai_support_threads ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.ai_support_threads TO authenticated; GRANT ALL ON public.ai_support_threads TO service_role;
CREATE TABLE public.app_settings (key text NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, value jsonb NOT NULL, PRIMARY KEY (key));
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.app_settings TO authenticated; GRANT ALL ON public.app_settings TO service_role;
CREATE TABLE public.batch_settlements (batch_id uuid NOT NULL, confirmed boolean DEFAULT false NOT NULL, confirmed_at timestamptz, confirmed_by uuid, created_at timestamptz DEFAULT now() NOT NULL, customer_code text NOT NULL, id uuid DEFAULT gen_random_uuid() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.batch_settlements ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.batch_settlements TO authenticated; GRANT ALL ON public.batch_settlements TO service_role;
CREATE TABLE public.batches (actual_ship_date date, batch_no text, cargo_type text, closed_at timestamptz, container_no text, created_at timestamptz DEFAULT now() NOT NULL, created_by uuid, customs_consignee jsonb, customs_shipper jsonb, destination_code text, destination_codes text[] DEFAULT '{}'::text[] NOT NULL, display_name text, eta_date date, fee_breakdown jsonb, grand_total_cny numeric DEFAULT 0 NOT NULL, hbl_extracted jsonb, hbl_file_name text, hbl_file_path text, hbl_goods_description text, hbl_total_volume_m3 numeric, hbl_total_weight_kg numeric, id uuid DEFAULT gen_random_uuid() NOT NULL, notes text, planned_ship_date date NOT NULL, sequence_no integer, shipping_method public.batch_method NOT NULL, status public.batch_status DEFAULT 'draft'::public.batch_status NOT NULL, total_cny numeric, total_volume_cm3 numeric, total_weight_kg numeric, updated_at timestamptz DEFAULT now() NOT NULL, vessel_no text, waybill_count integer, PRIMARY KEY (id));
ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.batches TO authenticated; GRANT ALL ON public.batches TO service_role;
CREATE TABLE public.cargo_types (active boolean DEFAULT false NOT NULL, code text NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, id uuid DEFAULT gen_random_uuid() NOT NULL, name_en text, name_zh text NOT NULL, sort_order integer DEFAULT 0 NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.cargo_types ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.cargo_types TO authenticated; GRANT ALL ON public.cargo_types TO service_role;
CREATE TABLE public.cartons (address_snapshot jsonb, batch_id uuid, carton_no text, closed_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL, created_by uuid, customer_code text, customer_user_id uuid, destination_code text, display_name text, height_cm numeric, id uuid DEFAULT gen_random_uuid() NOT NULL, length_cm numeric, notes text, pallet_id uuid, pickup_warehouse text, route_code text, route_id uuid, self_freight_cad numeric DEFAULT 0 NOT NULL, self_freight_cny numeric DEFAULT 0 NOT NULL, self_height_cm numeric, self_length_cm numeric, self_volume_m3 numeric, self_weight_kg numeric, self_width_cm numeric, sequence_no integer, status text DEFAULT '' NOT NULL, unlocked boolean DEFAULT false NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, weight_kg numeric, width_cm numeric, PRIMARY KEY (id));
ALTER TABLE public.cartons ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.cartons TO authenticated; GRANT ALL ON public.cartons TO service_role;
CREATE TABLE public.cms_articles (author_id uuid, content_md text, cover_url text, created_at timestamptz DEFAULT now() NOT NULL, excerpt text, id uuid DEFAULT gen_random_uuid() NOT NULL, published_at timestamptz, slug text NOT NULL, status public.cms_status DEFAULT 'draft'::public.cms_status NOT NULL, title text NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.cms_articles ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.cms_articles TO authenticated; GRANT ALL ON public.cms_articles TO service_role;
CREATE TABLE public.cms_banners (created_at timestamptz DEFAULT now() NOT NULL, ends_at timestamptz, id uuid DEFAULT gen_random_uuid() NOT NULL, image_url text NOT NULL, is_active boolean DEFAULT false NOT NULL, link_url text, position text DEFAULT '' NOT NULL, sort_order integer DEFAULT 0 NOT NULL, starts_at timestamptz, title text NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.cms_banners ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.cms_banners TO authenticated; GRANT ALL ON public.cms_banners TO service_role;
CREATE TABLE public.contact_messages (created_at timestamptz DEFAULT now() NOT NULL, email text NOT NULL, id uuid DEFAULT gen_random_uuid() NOT NULL, message text NOT NULL, name text NOT NULL, phone text, status text DEFAULT '' NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.contact_messages TO authenticated; GRANT ALL ON public.contact_messages TO service_role;
CREATE TABLE public.coupon_redemptions (coupon_id uuid NOT NULL, id uuid DEFAULT gen_random_uuid() NOT NULL, order_id uuid, redeemed_at timestamptz DEFAULT now() NOT NULL, user_id uuid NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.coupon_redemptions ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.coupon_redemptions TO authenticated; GRANT ALL ON public.coupon_redemptions TO service_role;
CREATE TABLE public.coupons (code text NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, ends_at timestamptz, id uuid DEFAULT gen_random_uuid() NOT NULL, is_active boolean DEFAULT false NOT NULL, min_order_cny numeric DEFAULT 0 NOT NULL, name text, starts_at timestamptz, type public.coupon_type DEFAULT 'fixed'::public.coupon_type NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, usage_limit numeric, used_count integer DEFAULT 0 NOT NULL, value numeric DEFAULT 0 NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.coupons TO authenticated; GRANT ALL ON public.coupons TO service_role;
CREATE TABLE public.customer_hs_items (brand text, created_at timestamptz DEFAULT now() NOT NULL, ctns numeric, description text NOT NULL, hs_code text, id uuid DEFAULT gen_random_uuid() NOT NULL, items_per_carton numeric, material text, note text, origin text, sku text, unit_price_cad numeric, updated_at timestamptz DEFAULT now() NOT NULL, user_id uuid NOT NULL, weight_kg numeric, PRIMARY KEY (id));
ALTER TABLE public.customer_hs_items ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.customer_hs_items TO authenticated; GRANT ALL ON public.customer_hs_items TO service_role;
CREATE TABLE public.customs_rules (created_at timestamptz DEFAULT now() NOT NULL, enabled boolean DEFAULT false NOT NULL, id uuid DEFAULT gen_random_uuid() NOT NULL, note text, rate_pct numeric DEFAULT 0 NOT NULL, route_id uuid NOT NULL, threshold_cad numeric DEFAULT 0 NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.customs_rules ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.customs_rules TO authenticated; GRANT ALL ON public.customs_rules TO service_role;
CREATE TABLE public.delivery_queue (added_by uuid, code text NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, customer_code text, customer_user_id uuid, dispatched_at timestamptz, id uuid DEFAULT gen_random_uuid() NOT NULL, kind text NOT NULL, notes text, ref_id uuid NOT NULL, source_batch_id uuid, source_receiving_id uuid, status text DEFAULT '' NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.delivery_queue ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.delivery_queue TO authenticated; GRANT ALL ON public.delivery_queue TO service_role;
CREATE TABLE public.destinations (active boolean DEFAULT false NOT NULL, code text NOT NULL, country text, created_at timestamptz DEFAULT now() NOT NULL, id uuid DEFAULT gen_random_uuid() NOT NULL, name_en text, name_zh text NOT NULL, sort_order integer DEFAULT 0 NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.destinations ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.destinations TO authenticated; GRANT ALL ON public.destinations TO service_role;
CREATE TABLE public.detained_packages (created_at timestamptz DEFAULT now() NOT NULL, created_by uuid, customer_code text, domestic_tracking_no text NOT NULL, id uuid DEFAULT gen_random_uuid() NOT NULL, intake_parent_id uuid, intake_parent_kind text, intake_waybill_ids text[], note text, released_at timestamptz, released_by uuid, status text DEFAULT '' NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.detained_packages ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.detained_packages TO authenticated; GRANT ALL ON public.detained_packages TO service_role;
CREATE TABLE public.forwarding_items (created_at timestamptz DEFAULT now() NOT NULL, extras jsonb DEFAULT '{}'::jsonb NOT NULL, forwarding_id uuid NOT NULL, hs_code text, id uuid DEFAULT gen_random_uuid() NOT NULL, name text NOT NULL, quantity integer DEFAULT 0 NOT NULL, unit_price_cad numeric DEFAULT 0 NOT NULL, unit_price_cny numeric DEFAULT 0 NOT NULL, PRIMARY KEY (id));
ALTER TABLE public.forwarding_items ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.forwarding_items TO authenticated; GRANT ALL ON public.forwarding_items TO service_role;