import { ReturnReminderEditor } from './ReturnReminderEditor';
import {useEffect,useState,type ReactNode} from 'react';
import {useServerFn} from '@tanstack/react-start';
import {saveIntakeReminder,saveOrderNoteOnly,saveOrderReminderOnly} from '@/lib/intake-reminder.functions';
export function OrderNoteEditor({kind,row,onSaved}:{kind:'order'|'forwarding';row:any;onSaved:()=>Promise<unknown>}){
 const save=useServerFn(saveIntakeReminder);
 const [open,setOpen]=useState(false),[note,setNote]=useState(''),[remind,setRemind]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <div className="text-xs">{kind==='forwarding'&&row.return_reminder&&<span className="block text-amber-300">退运提醒已开启</span>}<div className="max-w-48 whitespace-pre-wrap text-slate-300">{row.note}</div><button type="button" className="text-brand" onClick={()=>{setNote(row.note||'');setRemind(!!row.intake_reminder);setError('');setOpen(true);}}>{row.intake_reminder?'🔔 已开启提醒 · 编辑备注':'备注 / 入库提醒'}</button>{open&&<div role="dialog" aria-modal="true" aria-label="修改订单备注" className="fixed inset-0 z-50 flex items-center justify-center bg-black/70"><div className="w-full max-w-lg space-y-4 rounded-xl bg-slate-900 p-6 text-left"><h2>订单备注 · {row.request_no||row.order_no}</h2><textarea aria-label="订单备注" maxLength={4000} value={note} onChange={e=>setNote(e.target.value)} className="min-h-32 w-full rounded bg-slate-800 p-3"/><label className="flex gap-2"><input type="checkbox" checked={remind} onChange={e=>setRemind(e.target.checked)}/>入库时弹出提醒，要求工作人员查看备注</label>{kind==='forwarding'&&<ReturnReminderEditor row={row} onSaved={onSaved}/>} {error&&<p role="alert" className="text-red-400">{error}</p>}<div className="flex gap-4"><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await save({data:{kind,id:row.id,note,intake_reminder:remind}});await onSaved();setOpen(false);}catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}}>保存</button><button disabled={busy} onClick={()=>setOpen(false)}>取消</button></div></div></div>}</div>;
}

export function OrderNoteCard({kind,row,onSaved,children}:{kind:'order'|'forwarding';row:any;onSaved:()=>Promise<unknown>;children?:(parts:{notes:ReactNode;reminder:ReactNode})=>ReactNode}) {
 const saveNote=useServerFn(saveOrderNoteOnly),saveFlag=useServerFn(saveOrderReminderOnly);
 const [note,setNote]=useState(row.note||''),[remind,setRemind]=useState(!!row.intake_reminder),[busy,setBusy]=useState(false),[noteMessage,setNoteMessage]=useState(''),[flagMessage,setFlagMessage]=useState('');
 useEffect(()=>{setNote(row.note||'');},[row.id,row.note]);
 useEffect(()=>{setRemind(!!row.intake_reminder);},[row.id,row.intake_reminder]);
 const run=async(which:'note'|'flag')=>{const message=which==='note'?setNoteMessage:setFlagMessage;setBusy(true);message('');try{if(which==='note')await saveNote({data:{kind,id:row.id,note}});else await saveFlag({data:{kind,id:row.id,intake_reminder:remind}});await onSaved();message('已保存');}catch(e){message(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}};
 const notes=<div className="mt-4 border-t border-white/10 pt-3"><label className="block text-xs text-slate-300">订单备注<textarea disabled={busy} maxLength={4000} value={note} onChange={e=>{setNote(e.target.value);setNoteMessage('');}} placeholder="填写入库需要额外操作的事项……" className="mt-2 min-h-24 w-full rounded-md border border-white/10 bg-slate-900 p-3 text-sm text-slate-100"/></label><button type="button" disabled={busy} className="mt-2 rounded bg-brand px-3 py-1.5 text-xs text-white disabled:opacity-50" onClick={()=>run('note')}>保存备注</button>{noteMessage&&<p role="status" className="mt-2 text-xs text-amber-200">{noteMessage}</p>}</div>;
 const reminder=<div className="mt-4 border-t border-white/10 pt-3">{kind==='forwarding'&&<ReturnReminderEditor row={row} onSaved={onSaved}/>}<label className="flex items-center gap-2 text-sm text-amber-200"><input type="checkbox" disabled={busy} checked={remind} onChange={e=>{setRemind(e.target.checked);setFlagMessage('');}}/>开启入库特别提醒</label><p className="mt-2 text-xs text-slate-400">入库时弹出客户卡片中的订单备注，工作人员确认后继续。请先保存备注。</p><button type="button" disabled={busy} className="mt-2 rounded bg-brand px-3 py-1.5 text-xs text-white disabled:opacity-50" onClick={()=>run('flag')}>保存提醒设置</button>{flagMessage&&<p role="status" className="mt-2 text-xs text-amber-200">{flagMessage}</p>}</div>;
 return children?<>{children({notes,reminder})}</>:<section className="rounded-2xl border border-white/10 p-4">{notes}{reminder}</section>;
}
