import {PartnerDeliveryTest,type DeliveryApi} from './PartnerDeliveryTest';
import { useState } from 'react';
import './partner-route-settings.css';
const defaults={name:'加拿大海运 · 普货',code:'',method:'sea',cargo:'general',enabled:false,domesticRate:'30',domesticDensity:'200',domesticCurrency:'USD',seaRate:'',seaDensity:'',seaCurrency:'USD',portRate:'',portCurrency:'CAD',fx:'',originName:'',originPhone:'',originStreet:'',originCity:'',originProvince:'',originPostal:'',carrier:'',audience:'指定同行客户',customers:'',editors:'管理员',allowQuote:true,allowOrder:false};
type Draft=typeof defaults;
export function PartnerRouteSettings({embedded=false,deliveryApi}:{embedded?:boolean;deliveryApi?:DeliveryApi}){
 const [draft,setDraft]=useState<Draft>(()=>{try{return {...defaults,...JSON.parse(localStorage.getItem('partner-route-settings-preview')||'{}')}}catch{return defaults}});
 const [notice,setNotice]=useState(''),[section,setSection]=useState('basic');
 const update=(key:keyof Draft,value:string|boolean)=>{setDraft(d=>({...d,[key]:value}));setNotice('');};
 const field=(key:keyof Draft,label:string,unit='',placeholder='待填写')=><label>{label}<div className="prs-input"><input value={String(draft[key])} type={['domesticRate','domesticDensity','seaRate','seaDensity','portRate','fx'].includes(key)?'number':'text'} min={key.includes('Density')||key==='fx'?'0.000001':'0'} step="any" placeholder={placeholder} onChange={e=>update(key,e.target.value)}/>{unit&&<span>{unit}</span>}</div></label>;
 const select=(key:keyof Draft,label:string,options:[string,string][]) =><label>{label}<select value={String(draft[key])} onChange={e=>update(key,e.target.value)}>{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>;
 const currencies:[string,string][]=[['USD','USD · 美元'],['CAD','CAD · 加币']];
 const valid=(s:string,zero=false)=>s.trim()!==''&&Number.isFinite(Number(s))&&(zero?Number(s)>=0:Number(s)>0);
 const checks=[['基本资料',!!draft.name.trim()&&!!draft.code.trim()],['国内费用',valid(draft.domesticRate,true)&&valid(draft.domesticDensity)],['海运费用',draft.method==='sea'&&valid(draft.seaRate,true)&&valid(draft.seaDensity)],['目的港费用',valid(draft.portRate,true)],['派送发货资料',[draft.originName,draft.originPhone,draft.originStreet,draft.originCity,draft.originProvince,draft.originPostal,draft.carrier].every(x=>x.trim())],['USD → CAD 汇率',valid(draft.fx)],['客户权限',draft.audience==='全部同行客户'||!!draft.customers.trim()]] as const;
 const sections=[['basic','01','基本资料'],['cost','02','费用与计费规则'],['origin','03','派送发货地点'],['access','04','访问权限']];
 return <div className={embedded?"prs prs-embedded":"prs"}><header><a href={embedded?"/partner-shipping":"http://127.0.0.1:4178/"}>eplus<span>+</span><small>同行业务后台</small></a><span className="prs-badge">本地设计预览</span></header><div className="prs-shell"><nav><div className="prs-nav-title">专属线路管理</div>{sections.map(([id,n,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}><span>{n}</span>{label}</button>)}<div className="prs-nav-note">独立于现有集运线路<br/>配置完成后再接入报价</div></nav><main><div className="prs-heading"><div><div className="prs-eyebrow">PARTNER / ROUTE SETTINGS</div><h1>同行专属线路设置</h1><p>一条线路，统一管理费用、派送起点与客户使用范围。</p></div><span className="prs-draft">草稿 · 未发布</span></div><div className="prs-banner">当前只保存本浏览器草稿。线路、API、权限均未写入后台，不影响现有业务。</div><div className="prs-layout"><div>
 {section==='basic'&&<section><h2>基本资料 <small>决定客户可选择的运输方案</small></h2><div className="prs-grid">{field('name','线路名称','','例如：加拿大海运 · 普货')}{field('code','线路编号','','例如：PARTNER-SEA-CA-01')}{select('method','运输方式',[['sea','海运'],['air','空运（计费方式待确认）']])}{select('cargo','货物类型',[['general','普货'],['sensitive','敏感货']])}</div><label className="prs-toggle"><input type="checkbox" checked={draft.enabled} onChange={e=>update('enabled',e.target.checked)}/>计划启用此线路 <small>仅草稿状态，不会实际开放</small></label><div className="prs-note">收件国家：加拿大 · 通过专属链接登录使用 · 前端菜单暂不增加入口</div></section>}
 {section==='cost'&&<><section><h2>国内费用 <small>体积与重量折算取大值</small></h2><div className="prs-grid three">{field('domesticRate','每立方单价','/ m³')}{field('domesticDensity','每立方折算重量','kg/m³')}{select('domesticCurrency','费用币种',currencies)}</div><div className="prs-formula">max（总体积，总实重 ÷ {draft.domesticDensity||'折算重量'}）× {draft.domesticRate||'单价'} {draft.domesticCurrency}</div></section><section><h2>{draft.method==='sea'?'海运费用':'空运费用'} <small>每条线路独立设置</small></h2>{draft.method==='sea'?<><div className="prs-grid three">{field('seaRate','每立方单价','/ m³')}{field('seaDensity','每立方折算重量','kg/m³','例如 300，需自行确定')}{select('seaCurrency','费用币种',currencies)}</div><div className="prs-formula">max（总体积，总实重 ÷ {draft.seaDensity||'折算重量'}）× {draft.seaRate||'单价'} {draft.seaCurrency}</div></>:<p className="prs-note">空运费计算方式待确认，不套用海运参数。</p>}</section><section><h2>目的港费用 <small>仅按总体积计算</small></h2><div className="prs-grid">{field('portRate','每立方单价','/ m³')}{select('portCurrency','费用币种',currencies)}</div><div className="prs-formula">总体积 × {draft.portRate||'单价'} {draft.portCurrency}</div></section><section><h2>关税与派送费</h2><div className="prs-rule"><b>关税</b><p>各品名总货值 × HS 编码税率，再合计。税率沿用编码库 MFN + GST + 反倾销；缺失时提示补齐。</p></div><div className="prs-rule"><b>派送费</b><p>由快递面单 API 查询报价。使用本线路发货地点、客户地址及包裹尺寸和实重；查询不创建面单。</p></div></section><section><h2>包裹重量规则 <small>已确认规则 · 当前只读</small></h2><div className="prs-metrics"><div><b>6000</b><span>体积重除数</span></div><div><b>0.5 kg</b><span>向上进位</span></div><div><b>10 kg</b><span>单包最低计费重</span></div></div><p className="prs-note">长 × 宽 × 高 ÷ 6000；与实重取大值后逐包进位，再汇总。国内与海运折算使用总实重。</p></section><section><h2>报价币种与汇率</h2><div className="prs-grid"><label>客户报价币种<input value="CAD · 加币" readOnly/></label>{field('fx','1 USD 折合 CAD','CAD')}</div><p className="prs-note">币种不同先换算再合计；汇率或任一必要费用缺失时，不生成完整报价。</p></section></>}
 {section==='origin'&&<><section><h2>派送发货地点 <small>提供给快递面单 API 的寄件地址</small></h2><div className="prs-grid">{field('originName','发货人 / 公司')}{field('originPhone','联系电话')}</div><div className="prs-gap">{field('originStreet','详细地址','','街道、门牌、单元号')}</div><div className="prs-grid three prs-gap">{field('originCity','城市')}{select('originProvince','省份 / 地区',[['','请选择省份'],...['AB','BC','MB','NB','NL','NS','NT','NU','ON','PE','QC','SK','YT'].map(x=>[x,x] as [string,string])])}{field('originPostal','邮编')}</div><p className="prs-note">国家：Canada。每条线路绑定一个发货地点，客户不需要填写发货资料。</p></section><section><h2>快递报价来源</h2>{field('carrier','快递账号 / 服务标识','','待关联现有快递面单系统')}<p className="prs-note">这里将选择现有系统已配置的账号或服务，不填写 API 密钥。报价联调见下方，只查询价格。</p></section><PartnerDeliveryTest key={[draft.originName,draft.originPhone,draft.originStreet,draft.originCity,draft.originProvince,draft.originPostal].join('|')} api={deliveryApi} origin={{name:draft.originName,company:draft.originName,mobile_phone:draft.originPhone,region_id:'CA',province:draft.originProvince,city:draft.originCity,postalcode:draft.originPostal,address:draft.originStreet,address2:'',email:'',type:'commercial'}}/></>}
 {section==='access'&&<section><h2>访问权限 <small>配置方案预览 · 尚未生效</small></h2><div className="prs-grid">{select('audience','哪些客户可使用',[['指定同行客户','指定同行客户'],['全部同行客户','全部同行客户']])}{select('editors','后台可编辑角色',[['管理员','管理员'],['管理员和授权运营','管理员和授权运营']])}</div>{draft.audience==='指定同行客户'&&<div className="prs-gap">{field('customers','指定客户号','','用逗号分隔，后台接入后改为客户选择器')}</div>}<label className="prs-toggle"><input type="checkbox" checked={draft.allowQuote} onChange={e=>update('allowQuote',e.target.checked)}/>允许查询价格</label><label className="prs-toggle"><input type="checkbox" checked={draft.allowOrder} onChange={e=>update('allowOrder',e.target.checked)}/>允许提交运单 <small>仅草稿选项，下单功能尚未接入</small></label><div className="prs-note">专属链接仍需登录并校验客户权限。实际角色授权和客户关联将在后台接入时实施。</div></section>}
 <div className="prs-actions"><span role="status">{notice||'修改后可保存为本地草稿，便于继续讨论。'}</span><button onClick={()=>{try{localStorage.setItem('partner-route-settings-preview',JSON.stringify(draft));setNotice('已保存本地草稿 · 未写入后台')}catch{setNotice('本地保存失败，请检查浏览器存储权限')}}}>保存本地草稿</button></div></div><aside><div className="prs-summary-title">线路配置概览</div><h3>{draft.name||'未命名线路'}</h3><p>{draft.method==='sea'?'海运':'空运'} / {draft.cargo==='general'?'普货':'敏感货'} / 加拿大</p><div className="prs-completion"><b>{checks.filter(x=>x[1]).length}<small> / {checks.length}</small></b><span>项资料已填写</span></div>{checks.map(([name,ok])=><div className="prs-check" key={name}><span>{name}</span><b className={ok?'ok':''}>{ok?'已填写':'待补充'}</b></div>)}<p className="prs-summary-note">这是完整性提示，非后端校验结果。后台页面、账号关联和权限控制仍待接入。</p><a href={embedded?"/partner-shipping":"http://127.0.0.1:4178/"}>查看客户询价页面 ↗</a></aside></div></main></div></div>;
}
