// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhfsrrbzubgjrjhgwerv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoZnNycmJ6dWJnanJqaGd3ZXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAwMzM5NzcsImV4cCI6MjEwNTYwOTk3N30.4796UaHfTi4cm7cV2dS3cKXXmRSKHing5bbDc8aoOT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});